language: node_js
node_js:
- node
script:
- npm test
- npm run build
deploy:
  provider: s3
  access_key_id:
    secure: kh8uv5HiZSAXR/eSIRSyhj3MCGNnAWLVDfmdRGdfJSpQ8lw4Oncw3/eqDnYgHF+GYie3m+ObEHsR5ySIIcFtYtbir6OVV3BPMRu33ZbSyD0cN/oZjRmnfSDcFkcv0gYT5tILrbOafijtrUrs3Foq9dgVyQxw9n3JkLnk8/6dNfk3K5HujNw9D8iECbTHLYvwdjaj8YObneAKNYxuwUq8AyG2czSF5APMwik8GfVaaypbHrIt8EHeWjoGqV84Z0mSbML+heM0rkzeQ3G6HUXXMqno+ngP5ySzI/JUcOzygOflLB6OQt9hQ9G2IRXbby4C0D9SZTdPG840qpqN7VnwR41breoLo9zhYOO9LSY42Uzx5EGMEw3KRMyIhZmkeKomd7QtUyzqKM9wko4Qo/9mQq3XdB3ItBwj/BTbMXKQhLEcv//QlCVE0DbklJyCI31ibxFvTPeYmY2xE3wTgbniNhyA5Mx2FYdrXeG+p3HcsYGonlb1ZBoJWPcvKGLC7L/osfEnEtcb1itnsvHFQBRSQdXNQ0mi85CYpULEEHqVtDTxXnxjdoPH5zaMilLNk2qDsc0A86x18LojfRxaoA8V4yaP5ZeNiS4s2ITJTbt7tPzoQUSTHoVvdHJwYUdnHE8jcHYo4N006tZHVc428y9KNF5A/dy8NDZurj57vWNidKM=
  secret_access_key:
    secure: Dg2Ha97XcFg/JdnNPfH+ySoSlVkwh2gZsw7/Xlh4dxKyTdyhK0+jOWc8ZVh1lVJzE/hMjTSUcH43lp5WXVMlYy2tDYWfoZIZKoamrAAJQ6/4aIBVlT3zYqold1DRWayhLsOEGgxYUb+cS1OIJh5Zn47I53tH4AZduUsvgF1gzJM632qkgGdXNiqIpcEnzSt5//v0YwK1ds5R87tQTh7hnxck8yUgAYfJCOHDt5/2kdrOcCII0Ouu0LO/eeLVH0segV+RkpDGJsng9yavDPoLqmsQESP9XjvbhB5zCc0pEU0H6fCwnTQXCw0Z7xKves3ffH0yXA03IBtxccLPFh0yCXFxPJr8e668euQerX8PYdUCGJNXV1l43MalBU+yI+ZtCwSy4Gw65s8bX85t5nqvI0W1oDuSA3xwgY1WNVxEaTIO0zAaBw7x8AOsqESiRhLMYUT1fB4pDjTthRmEmGH5luWUAp96iiJ7XNSO832zLdhM6sUDWGiE7ahGS7GWs7mVqBjX3eW6hSjUWYQoiV7kL+SK/miDEG/DtdSBDxzdp53ljtIM3xg6qgx4/i5TC5LYQ9nO/vbhkaOIFKDk1YMo5xwcND2Ro5MCkF+h9l0sJdsXmrfCX3rqT9aH3nddI6psTrX3hDS6PQ0yDdfjuBovq8DKrSw+/4KOXOlno6fXV8E=
  bucket: notedown-react
  local-dir: dist
  skip_cleanup: true
  upload-dir: static
  on:
    repo: sambokai/Notedown
