language: node_js
node_js:
- node
script:
- npm test
- npm run build
deploy:
  provider: s3
  access_key_id:
    secure: "CngbG17fcZzf1nBouXMgddX3j7GA7Xm+LUFUAkG9lKNHTDBXa6eb22/umhFWPtfeJoPM3dX43m/Qa+IM51VEpvlSVlbhfwkng5V5oL4P4Dt85R6wusEl2PpmCLfXVdPaYyUyxbDoQoh3Jvx1nCVN18qplcf/iKUNdG7F7k1jJxwe4hCseEramU7mi4jG6FuLWGfuYLbBRCjFbRp+VuoGEpnoHvNiCWK2XWri2R+7NeAYW32etyEB7rPf1St6k7rHY6CyoYpPPvbA3fpi0cu8f62FrtiUDbayFsbvRcVKeOeE7z5Rtu2fB4+dkPkwU2qTBy2l93Eu1YFpNUPMrMHh6Zf6r/57Nl4Oi6IrirzMeX8Cu7hMAk8c9B3YrxP3S9r0UQXXbuJNwrCIG2pO3Kt1PUubvKfEsc2NOrhqZmLqddixk3I5DjuUgN4T84Ah8ysCxjOGBUgQLFcTMAjeuZCpgaSRbgIPTH0jEp+ihfd1tiQYHgefz5rytkFtZzrjJ/wQGvjhSWU94u7yQS33LeW9JGfar6/ndkfMp318AQ1pl8efFSVCBsBkqyBk+vmr8lV17X8j25wUcQWN74Ca99/KQjhKrbhTxhWQyENumaKhu5veVJh/tcoPuqAoaccUqp5brW8/O/iL7xC33CWI1uUlcNRn76lYU+2ZcL6It7obu6Q="
  secret_access_key:
    secure: "xrPNshbubZ9UytlKMJUf9nBLhLb4We8XyVMzJ6iYSerjigM1sBS70QV/r13/T1+GNWhSgwGzplu7P33WVvrGH+ZepxiY/F8UU7ofUvjockeWZW6oiMPB2vE7RN9Nry4/Q7bpCN6H0uk0A4A2cGO3/7MKDJXBba0Kn2dgvbA9HMmPHbNX9xLH+UBjmO9kx67sovIWZPjkj5hIrHOkR1fspQaCKfK5E16dUmQ/HM2u7LV+Sdy/6QQJ3hP5S9T73w1fssWCf/hhmBDvgrCiI1OOKWqbWIO08m+G6+8WMonAJw1TdUOQbzZlbieif/vjrxq8iiOGknDvjoVUOcQRKmmNY2xK1Ch4Oali2AXdI+KRq4dGuoCvYiGtInjZSjsgMND2avcOc52UKF+GZST9a46eXcIRQOe4BkG4Z5I0GnZwZttXn+xNUol6/1MfEmENv5AIe3TgBZkZM0ck+OixujI4S1/iqmg9zGu4KR8OhE75GLykYwnlVsj7c+qi3wDRUwI4FOA5ithXB7/fQTsY8VG2bdeXxA7Mhbx8WsF7+QA+FXJ26lagyZnZ8bK9AjvCwQA08eDRSHQajgy3xca9WDJ0kMpcDaJKes8En1UtrHwcB0oP89A/FhJmyFB/estHuycHbMELr9yqFd5pgmnjGYCQS4QCeuO7NvpMHoICNb+VBxo="
  bucket: notedown-react
  local-dir: dist
  skip_cleanup: true
  upload-dir: static
  on:
    repo: sambokai/Notedown
