dist: trusty
language: node_js
node_js:
- node
before_install:
- npm install -g codecov
script:
- npm run test:ci
- codecov
- npm run build
#cache:
#  directories:
#    - "node_modules"

sudo: required
addons:
  chrome: stable

deploy:
  provider: s3
  region: eu-central-1
  access_key_id:
    secure: ryk+FyHygnMCPO+/8XHpSqlhYtrtxCyxV/mRNehb4N2gF2wpO20A4DC4TjI+pRpRLmVH0n3jr6zqidIrWcArDdlLvMnojWdnAqq0i9aAEWUbGYJZtCCAAcpTsvrCAL2FeIwM6jT1lp0eOb+iLiLgmoDpf6jkOakekamhU0Lo147UwIrg4fZ8h3yKq7VPN1/F1+2a5iBsxY7C2L+1RewMFeNZukL7MfIrFcw59hyD7IFsUTtKq5o8F8lcbca8zr9BUCD+/+cNdn02+C54tlCC6BNKGJoOWAGQ2v7zl25xlI9K0otyntUCk91c/uNr1l4I2VYqyhzsWEAD9oxANF7ubrxRofkgbKubWGv/+WdrBxe8lALD4NqOlojdjnFn++1vp6E8VC4tKz7p9/KqQnrzhTqh2U2uq8y7vJaVQsp7nyLtn3Dyh4DbqvNy8wRQD/ntex7vz6ljUQM5R4VRfbFxpr1vIxWqsfHZ7BUm5fN7ZXw9DTkWwHETV6tzW4vaVuT4QjawYHiT+I3M9WGoVKLWDpCdCTUA6NfvHOj2VDsVlhQkd+UaaK2VvfQVh6vznUHBYcbSQeo/LE19FfiC1gsxbiGctbk0HQxIkT2f/4D6heCus7zbKYBZQ3J+SfP4oQmMAusH7/J49f9U6sVUOdUKU+JsVl7pegsF15I2HWnURTQ=
  secret_access_key:
    secure: Bb2mECQx2GY1uFjCA4exnc3s3ihl81qV625uAjNUjHcmFEcL9pCk2c3QCbUqN0fqhUIej3UzwdJ/JV4q7gHny9eocNo09CbVk6b+fGeABUmoweX4sS7GQXZj0EQfGdsIlUZ6Y6fs5JgRZrUm5jNjwRcIkcdhwThe9vdIhYrWbCOfl8CayvJhK03rGqzKkpf1+FxhPRtbVPimKuQXIbwaHouEPK6WNlwpQZ9W+G5ybYLdZOOfpHuqLlBRysBdvSDr4cgayfxJiD8kFUg4Sy344hUc7NcwcpJ/zHFAVe5TVRfXxnGdYRP/ozOoUA7fbleI5TCdJ2pQSvWecVRFbkyZqqvy1Z5wcsgSymI2BqXX4HmIZ9wSzfSPivG3uVh2h9tnF8XX4Xu1uILJLiQ7xcI0NdlijWUKpXDAlXraKUbYIuubDJm5x1eBdQzX/eZPObsXdmnk9M/B2PtxKCcy2mbF/00lkaBtFJey/6iLAGFz/20fx220oAQFrebKwa098xtTR7hJhIJtHfe0NOnwTNdDcwn1Zx5RjS0cUVmXxVOb4dIIGSuQ/NR8P7x0Wk8Wokf3oNWv+DKCX6twxrKAMepP/+7ZNElvYHQ5bXkonOo0EPlEdCQfhe8WvCOPtjFWYaVrRN02SEQo8q57He9t71ryWL3cWUoNiZKFNA7HAF/mzhs=
  bucket: notedown.sambokai.com
  local-dir: dist
  skip_cleanup: true
  on:
    repo: sambokai/Notedown
